--- 
title: "Analysis of the US Stock Market through the COVID-19 Lens"
author: "Gangadhara Reddy | Rahulraj Singh"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Coronavirus, since it's first news in December 2019 has changed almost every aspect of our lives. On March 11, 2020, WHO declared COVID-19 a global pandemic and March 12 was declared a Black Thursday in the United States, giving in to the largest single day market crash since 1987. This was no coincidence. The pandemic had officially started crippling world economy. Stock Markets do not deal well with uncertainity, as history has often shown us, this was going to be one of the most uncertain periods of time mankind had seen. 

But not all has gone bad. Over the past 2 years of living with the pandemic, we as humans have grown and evolved, as we always do. Companies like Apple and Microsoft saw their all time highs during the pandemic while there were companies that went bankrupt and closed. So, what factored into these radical differences? What happened in the last 2 years that flourished some, while whitewashed others? In this project, we aim to solve this mystery.

## Problem Statement

Below are some of the formal questions we would be attempting to answer:

1. Analysis of repetitive patterns in companies to understand the impact of annual events (Christmas, Halloween, Black Friday, etc.) and quarterly events (dates of SOFR announcement, quarterly earnings report, etc.) on different industries.
2. Observe the people’s confidence in the stock market throughout COVID-19 by analyzing the behavior of stock fluctuations in various sectors of the economy (agriculture, healthcare, consumer good, electronics, technology, etc.)
3. Superimpose that analysis to specific companies that were in the news for production of vaccines. Analyse the difference in performance of vaccine-producing pharmaceutical companies to other industries throughout COVID-19.